services:
  yaffle:
    image: ghcr.io/sigmaris/yaffle:latest
    init: true
    environment:
      QUICKWIT_URL: http://quickwit:7280
    ports:
      - "8088:8088/tcp"
  quickwit:
    image: quickwit/quickwit:qw-0.5.1-multiarch
    init: true
    environment:
      QW_ENABLE_OTLP_ENDPOINT: false
      QW_ENABLE_JAEGER_ENDPOINT: false
    command:
      - run
    ports:
      - "7280:7280/tcp"
