services:
  yaffle:
    image: ghcr.io/sigmaris/yaffle:latest
    init: true
    environment:
      - TOSHI_URL=http://toshi:8080
  toshi:
    image: ghcr.io/sigmaris/toshi:latest
    init: true
    ports:
      - "8080:8080/tcp"
