name: Build Project

on:
- push
- pull_request

jobs:
  dev_build:
    name: Build (Dev)
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout yaffle
      uses: actions/checkout@v2
      with:
        path: yaffle
    - name: Checkout Toshi
      uses: actions/checkout@v2
      with:
        repository: sigmaris/Toshi
        path: Toshi
    - run: cd "${GITHUB_WORKSPACE}/yaffle" && cargo test
    - run: cd "${GITHUB_WORKSPACE}/yaffle" && cargo build
