name: Build Project

on:
- push
- pull_request

jobs:
  dev_build:
    name: Build (Dev)
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout yaffle
      uses: actions/checkout@v3
    - run: cargo install cargo-leptos
    - run: cargo leptos test
