name: clippy
on: [pull_request]
jobs:
  clippy:
    name: Report clippy lints
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout yaffle
      uses: actions/checkout@v2
      with:
        path: yaffle
    - name: Checkout Toshi
      uses: actions/checkout@v2
      with:
        repository: sigmaris/Toshi
        path: Toshi
    - name: Run clippy
      uses: sigmaris/action-clippy@debian_image
      with:
        workdir: yaffle
        level: warning
        clippy_flags: '--verbose'
