name: clippy
on: [pull_request]
jobs:
  clippy:
    name: Report clippy lints
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout yaffle
      uses: actions/checkout@v3
    - name: install clippy
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
    - name: Annotate commit with clippy warnings
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
